In [13]:
from sklearn.preprocessing import OneHotEncoder


In [1]:
import pandas as pd

In [75]:
problem = "medium"
df_filter = pd.read_csv('renault/config_' + problem + '_filtered.txt', sep=" ")
with open('renault/index_csv_' + problem + '.txt', 'r') as foldtxt:
    fold = foldtxt.read().replace('\n', '')

num_validation_fold = 4

print(int(fold[4]))

hist_tab_filter = df_filter.values[[i for i in df_filter.index if int(fold[i]) != num_validation_fold]]
print(type(hist_tab_filter))
df_filter.head()


7
<class 'numpy.ndarray'>


v1  v2  v3  v4  v5  v6  v8  v9  v10  v11  ...  v41  v44  v46  v47  v48  \
0   2  11   1   0   1   0   2   0    1    0  ...   -1    0    5    1    1   
1   2  11   1   0   1   0   2   0    1    0  ...   -1    0    5    1    1   
2   2  11   1   0   1   0   2   0    1    0  ...   -1    0    5    1    1   
3   2  11   1   0   1   0   2   0    1    4  ...   -1    0    5    1    1   
4   2  11   1   0   1   0   2   0    1    0  ...   -1    0    5    1    1   

   v49  v50  v118  v53  v54  
0    0    0    14    2    0  
1    0    0    14    2    0  
2    0    0    14    2    0  
3    0    0    14    2    0  
4    0    0    14    2    0  

[5 rows x 44 columns]

In [16]:
import numpy as np
import pickle

In [114]:
domain_dict = pickle.load(open('renault/domain_' + problem + '.pkl', "rb"))

scope_filter = list(df_filter.columns)

sorted_domain_dict = {}
for k in list(scope_filter):
    sorted_domain_dict[k] = np.sort(domain_dict[k])

print(domain_dict[scope_filter[5]])
print([sorted_domain_dict[k] for k in list(scope_filter)])

onehotencoder = OneHotEncoder(categories=[sorted_domain_dict[k] for k in list(scope_filter)])
data = onehotencoder.fit_transform(hist_tab_filter).toarray()
data = np.array(data, dtype=int)
print(data[0])

[0 1]
[array([0, 1, 2, 3]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), array([0, 1, 2]), array([0, 1]), array([0, 1]), array([0, 1]), array([0, 1, 2]), array([0, 1]), array([0, 1]), array([0, 1, 2, 3, 4]), array([0, 1]), array([0, 1, 2, 3, 4, 5, 6, 7]), array([0, 1]), array([0, 1, 2, 3]), array([0, 1]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]), array([0, 1]), array([0, 1]), array([0, 1]), array([0, 1]), array([0, 1]), array([0, 1]), array([0, 1]), array([0, 1]), array([0, 1]), array([0, 1]), array([0, 1]), array([0, 1, 2, 3, 4, 5]), array([0, 1, 2, 3]), array([0, 1, 2, 3, 4]), array([0, 1]), array([0, 1]), array([-1,  0]), array([0, 1]), array([-1,  0]), array([0, 1]), array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([0, 1]), array([0, 1]), array([0, 1]), array([0, 1, 2]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]), array([0, 1, 2, 3, 4, 5, 6]), array([-1,  0])]
[0 0 1 0 0 0 0 0 0 0 0 0 0 

In [25]:
print(data[0])
print(hist_tab_filter[0])

[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 1 0 0 0 1 1 0 0 1 1 0 0 0
 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1
 0 1 0 1 0 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0
 1 1 0 1 0 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1]
[ 2 11  1  0  1  0  2  0  1  0  0  2  1  2  1  6  0  0  0  1  1  1  1  0
  0  0  0  5  1  2  1  0 -1  1 -1  0  5  1  1  0  0 14  2  0]


In [76]:
# read latin squares data file
import json

with open("instance0.json", "r") as datafile:
    dict_data = json.load(datafile)

sq_dim = len(dict_data['solutions'][0]['square'][0])
list_data = list()
for square_dict in dict_data['solutions']:
    square_data = [nb for row in square_dict['square'] for nb in row]

    list_data.append(square_data)


np_data = np.asarray(list_data)
print(np_data)

[[1 2 3 ... 3 2 1]
 [1 4 6 ... 1 8 2]
 [3 1 8 ... 9 7 2]
 ...
 [8 3 2 ... 7 2 9]
 [8 3 2 ... 7 2 9]
 [8 3 2 ... 7 2 9]]


In [115]:
# ONE HOT 3 DIMENSIONS 100 010 001 

dom = [*range(1, sq_dim + 1)]
all_domains = [np.asarray(dom) for _ in range(sq_dim*sq_dim)]

onehotencoder = OneHotEncoder(categories=all_domains)
data = onehotencoder.fit_transform(list_data).toarray()
data = np.array(data, dtype=int)
print(data[0])

[1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0
 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 1 